Added Nav Bar and Fragment Pages
Theillusionofthegift/FreshShare pull request #2
Opened 2021-05-14 19:28 UTC by ChrisNavoczynski

- Navigation Bar Added
- Fragments and corresponding XML files created for Nav Bar to work.
- Color scheme and Strings Res files
![NewNav](https://user-images.githubusercontent.com/52547964/118319579-d02fc480-b4af-11eb-9464-d4f8c07dec94.PNG)

![NewNav2](https://user-images.githubusercontent.com/52547964/118319539-c4440280-b4af-11eb-98c7-3207f844691b.PNG)

2021-05-14 19:37 UTC, Theillusionofthegift requested changes
Hey it looks like you commit a local.properties` that shouldn't be

2021-05-14 19:37 UTC, Theillusionofthegift commented on local.properties
> +## This file must *NOT* be checked into Version Control Systems,
Hey it looks like you commited a local.properties that shouldn't be

2021-05-14 20:06 UTC, Theillusionofthegift approved these changes
Looks good!

2021-05-15 15:43 UTC, mfern08 approved these changes
I think it looks great! Everything checks out :)

2021-05-15 18:46 UTC, mfern08 approved these changes
I think it looks great! Everything checks out :)

2021-05-15 20:37 UTC, merged